<?php

	$ocdi_fields_to_change = array(
	    'options_global_page_brand_color' => '#718091',
	    'options_global_page_background_size' => 'auto',
	    'options_global_page_background_repeat' => 'repeat',
	    'options_global_page_text_typo' => '{"color":"#5e646a","font_family":"Poppins","font_variants":["300","regular","500","600","700"],"font_subsets":["latin"]}',
	    'options_global_page_headings_typo' => '{"color":"#373c40","weight":"500","font_family":"Poppins","font_variants":["300","regular","500","600","700"],"font_subsets":["latin"]}',
	    'options_global_page_subtitles_typo' => '{"color":"#718091","font_family":"Poppins","font_variants":["300","regular","500","600","700"],"font_subsets":["latin"]}',
	    'options_global_page_smooth_scroll' => '1',
	    'options_global_page_is_wrapped' => '1',
	    'options_global_header_menu_use_wrapper' => '0',
	    'options_global_header_menu_text_typo' => '{"color":"#000000"}',
	    'options_global_header_menu_border_type' => 'solid',
	    'options_global_header_menu_hide_contacts_bar' => '0',
	    'options_global_header_menu_contacts_bar_phone_numbers' => '',
	    '_options_global_header_menu_contacts_bar_phone_numbers' => 'field_59229bda35af2',
	    'options_global_header_menu_contacts_bar_emails' => '',
	    '_options_global_header_menu_contacts_bar_emails' => 'field_59229bda35ef5',
	    'options_global_header_menu_contacts_bar_additional' => '',
	    '_options_global_header_menu_contacts_bar_additional' => 'field_59229bda3630a',
	    'options_global_header_menu_contacts_bar_social_links' => '',
	    '_options_global_header_menu_contacts_bar_social_links' => 'field_59229bda366f4',
	    'options_global_header_background_color' => '#f5fafd',
	    'options_global_header_use_overlay' => '0',
	    'options_global_header_tilte_typo' => '{"color":"#373c40"}',
	    'options_global_header_title_align' => 'left',
	    'options_global_header_height' => '400px',
	    'options_global_footer_background_color' => '#34373a',
	    'options_global_footer_is_sticky' => '1',
	    'options_global_footer_copyright_text' => '&copy; 2017, norebro theme by <a href="#" target="_blank">Colabr.io Team</a>, All right reserved.',
	    '_options_global_footer_copyright_text' => 'field_592fd8901f24b',
	    'options_global_footer_copyright_text_color' => '#707479',
	    'options_global_footer_copyright_background_color' => '#34373a',
	    'options_global_side_panel_background' => '#ffffff',
	    'options_global_side_panel_color' => '#373c40',
	    'options_global_side_panel_text' => '&copy; 2017, Norebro theme by <a href="#" target="_blank">Colabr.io</a>',
	    'options_global_side_panel_social' => 'a:4:{i:0;s:8:"facebook";i:1;s:7:"twitter";i:2;s:10:"googleplus";i:3;s:8:"linkedin";}',
	    'options_global_header_logo_by_default' => 'dark_variant',
	    'options_global_header_logo_when_fixed' => 'dark_variant',
	    'options_global_fullscreen_menu_style' => 'default',
	    'options_global_footer_copyright_left' => '&copy; 2017, Norebro Theme by <a href="#" target="_blank">Colabr.io Team</a> | <a href="#">Privacy Policy</a> | <a href="#">Sitemap</a>',
	    'options_global_footer_copyright_right' => 'All Rights Reserved.',
	    'options_global_project_layout_type' => 'type_5',
	    'options_global_project_show_navigation' => 'prev_n_next',
	    'options_global_project_hide_breadcrumbs' => 'no',
	    'options_global_project_social_sharing_buttons' => 'a:5:{i:0;s:8:"facebook";i:1;s:7:"twitter";i:2;s:10:"googleplus";i:3;s:9:"pinterest";i:4;s:8:"linkedin";}',
	    'options_global_project_navigation_position' => 'bottom',
	    '_options_global_project_navigation_position' => 'field_592fd66622a31amod',
	    'options_global_fullscreen_menu_text_typo' => '',
	    'options_global_header_menu_social_links_1_social_network' => 'googleplus',
	    'options_global_header_menu_social_links_2_social_network' => 'instagram'
	);