<?php

    // slider revolution slides
    $ocdi_slides_to_revolution = array(
        trailingslashit( get_template_directory() ) . 'demo/22/home.zip'
    );

    $ocdi_fields_to_change = array(
        'options_global_page_brand_color' => '#313638',
        'options_global_page_background_size' => 'auto',
        'options_global_page_background_repeat' => 'repeat',
        'options_global_page_text_typo' => '{"font_family":"Poppins","font_variants":["700","600","500","regular","300"],"font_subsets":["latin-ext","latin","devanagari"]}',
        'options_global_page_headings_typo' => '{"weight":"400","font_family":"Lora","font_variants":["regular","italic","700","700italic"],"font_subsets":["cyrillic-ext","latin","vietnamese","latin-ext","cyrillic"]}',
        'options_global_page_subtitles_typo' => '{"font_family":"Lora","font_variants":["700italic","700","italic","regular"],"font_subsets":["cyrillic","latin-ext","vietnamese","latin","cyrillic-ext"]}',
        'options_global_page_smooth_scroll' => '1',
        'options_global_header_menu_style' => 'style5',
        'options_global_logo_type' => 'sitename',
        'options_global_menu_type' => 'hamburger',
        'options_global_page_is_wrapped' => '1',
        'options_global_header_menu_fixed' => '0',
        'options_global_header_menu_use_wrapper' => '0',
        'options_global_header_menu_hide_border' => '0',
        'options_global_header_menu_border_type' => 'solid',
        'options_global_header_menu_hide_contacts_bar' => '0',
        'options_global_header_menu_contacts_bar_phone_numbers' => '1',
        '_options_global_header_menu_contacts_bar_phone_numbers' => 'field_59229bda35af2',
        'options_global_header_menu_contacts_bar_emails' => '',
        '_options_global_header_menu_contacts_bar_emails' => 'field_59229bda35ef5',
        'options_global_header_menu_contacts_bar_additional' => 'Book a table',
        '_options_global_header_menu_contacts_bar_additional' => 'field_59229bda3630a',
        'options_global_header_menu_contacts_bar_social_links' => '',
        '_options_global_header_menu_contacts_bar_social_links' => 'field_59229bda366f4',
        'options_global_header_menu_contacts_bar_background' => '#1f2123',
        'options_global_header_menu_contacts_bar_text_typo' => '{"size":"13px","color":"rgba(255,255,255,0.9)","height":"32px"}',
        'options_global_header_title_background_type' => 'image',
        'options_global_header_logo_when_fixed' => 'dark_variant',
        'options_global_header_menu_contacts_bar_phone_numbers_0_phone_numbers' => '8901 Marmora Road, Glasgow, D04',
        '_options_global_header_menu_contacts_bar_phone_numbers_0_phone_numbers' => 'field_59229bda6c954',
        'options_global_side_panel_position' => 'hide',
        'options_global_side_panel_text' => '&copy; 2017, Norebro theme by <a href="#" target="_blank">Colabr.io Team</a>, All right reserved.',
        'options_global_side_panel_social' => 'a:4:{i:0;s:8:"facebook";i:1;s:7:"twitter";i:2;s:10:"googleplus";i:3;s:8:"linkedin";}',
        'options_global_fullscreen_menu_style' => 'centered',
        'options_global_footer_is_sticky' => '1',
        'options_global_footer_copyright_left' => '&copy; 2017, Norebro Theme by <a href="#" target="_blank">Colabr.io Team</a> | <a href="#">Privacy Policy</a> | <a href="#">Sitemap</a>',
        'options_global_footer_copyright_right' => 'All Rights Reserved.',
        'options_global_fullscreen_menu_text_typo' => '',
        'options_global_header_menu_social_links_1_social_network' => 'instagram',
        'options_global_header_menu_social_links_2_social_network' => 'googleplus',
        'options_global_header_menu_subheader_items_left_0_items' => '8901 Marmora Road, Glasgow, D04',
        '_options_global_header_menu_subheader_items_left_0_items' => 'field_59229bda6c954',
        'options_global_header_menu_subheader_items_left' => '2',
        'options_global_header_menu_subheader_items_right' => '1',
        'options_global_header_menu_subheader_items_left_1_items' => '<a href="/demo22/booking/">Book a table</a>',
        '_options_global_header_menu_subheader_items_left_1_items' => 'field_59229bda6c954',
        'options_global_header_menu_subheader_items_right_0_items' => 'Working Time: 9.00 am - 12;00 pm',
        '_options_global_header_menu_subheader_items_right_0_items' => 'field_59229bda6c955',
    );