<?php
	// slider revolution slides
	$ocdi_slides_to_revolution = array(
		trailingslashit( get_template_directory() ) . 'demo/21/home_slider.zip'
	);

	// global settings
	$ocdi_fields_to_change = array(
		'options_global_side_panel_position' => 'right',
    'options_global_side_panel_text' => '© 2017, Norebro theme by <a href="#" target="_blank">Colabr.io</a>',
    'options_global_side_panel_social' => 'a:4:{i:0;s:8:"facebook";i:1;s:7:"twitter";i:2;s:10:"googleplus";i:3;s:8:"linkedin";}',
    'options_global_logo_type' => 'image',
    'options_global_logo_image_light' => '13',
    'options_global_logo_image_dark' => '14',
    'options_global_header_logo_when_fixed' => 'dark_variant',
    'options_global_header_menu_fixed' => '0',
    'options_global_header_menu_hide_border' => '0',
    'options_global_header_menu_border_type' => 'solid',
    'options_global_header_menu_height' => '60',
    'options_global_header_menu_hide_contacts_bar' => '0',
    'options_global_header_menu_contacts_bar_phone_numbers' => '',
    '_options_global_header_menu_contacts_bar_phone_numbers' => 'field_59229bda35af2',
    'options_global_header_menu_contacts_bar_emails' => '',
    '_options_global_header_menu_contacts_bar_emails' => 'field_59229bda35ef5',
    'options_global_header_menu_contacts_bar_additional' => '',
    '_options_global_header_menu_contacts_bar_additional' => 'field_59229bda3630a',
    'options_global_header_menu_contacts_bar_social_links' => '',
    '_options_global_header_menu_contacts_bar_social_links' => 'field_59229bda366f4',
    'options_global_header_use_overlay' => '0',
    'options_global_header_title_align' => 'left',
    'options_global_header_height' => '360px',
    'options_global_header_menu_background_color' => '#333333',
    'options_global_header_background_color' => '#ffffff',
    'options_global_header_tilte_typo' => '{"size":"42px","color":"#404044","weight":"600"}',
    'options_global_page_background_color' => '#f8f8f8',
    'options_global_page_background_size' => 'auto',
    'options_global_page_background_repeat' => 'repeat',
    'options_global_page_headings_typo' => '{"font_family":"Poppins","font_variants":["700","600","500","regular","300"],"font_subsets":["latin"]}',
    'options_global_page_smooth_scroll' => '1',
    'options_global_page_is_wrapped' => '1',
    'options_global_footer_copyright_left' => '© 2017, Norebro Theme by <a href="#" target="_blank">Colabr.io Team</a> | <a href="#">Privacy Policy</a> | <a href="#">Sitemap</a>',
    'options_global_footer_copyright_right' => 'All Rights Reserved.',
    'options_global_footer_logo_type' => 'custom',
    'options_global_side_panel_add_padding' => '0',
    'options_global_side_panel_background' => 'rgba(255,255,255,0.01)',
    'options_global_fullscreen_menu_style' => 'default',
    'options_global_footer_logo_image' => '14237',
    '_options_global_footer_logo_image' => 'field_592fd8901c689',
    'options_global_fullscreen_menu_text_typo' => '',
    'options_global_header_menu_social_links' => '',
	);