<?php

	// slider revolution slides
	$ocdi_slides_to_revolution = array(
		trailingslashit( get_template_directory() ) . 'demo/19/home_slider.zip'
	);

	$ocdi_fields_to_change = array(
	    'options_global_footer_copyright_left' => '&copy; 2017, Norebro Theme by <a href="#" target="_blank">Colabr.io Team</a> | <a href="#">Privacy Policy</a> | <a href="#">Sitemap</a>',
	    'options_global_footer_copyright_right' => 'All Rights Reserved.',
	    'options_global_footer_is_sticky' => '1',
	    'options_global_fullscreen_menu_style' => 'centered',
	    'options_global_fullscreen_menu_text_typo' => '',
	    'options_global_header_logo_when_fixed' => 'dark_variant',
	    'options_global_header_menu_border_color' => 'rgba(255,255,255,0.06)',
	    'options_global_header_menu_border_type' => 'solid',
	    'options_global_header_menu_contacts_bar_additional' => '',
	    '_options_global_header_menu_contacts_bar_additional' => 'field_59229bda3630a',
	    'options_global_header_menu_contacts_bar_emails' => '',
	    '_options_global_header_menu_contacts_bar_emails' => 'field_59229bda35ef5',
	    'options_global_header_menu_contacts_bar_phone_numbers' => '',
	    '_options_global_header_menu_contacts_bar_phone_numbers' => 'field_59229bda35af2',
	    'options_global_header_menu_contacts_bar_social_links' => '',
	    '_options_global_header_menu_contacts_bar_social_links' => 'field_59229bda366f4',
	    'options_global_page_is_wrapped' => '1',
	    'options_global_header_menu_fixed' => '0',
	    'options_global_header_menu_hide_border' => '0',
	    'options_global_header_menu_hide_contacts_bar' => '0',
	    'options_global_header_menu_social_links' => '',
	    'options_global_header_menu_style' => 'style5',
	    'options_global_header_menu_text_typo' => '{}',
	    'options_global_header_title_background_type' => 'image',
	    'options_global_logo_type' => 'sitename',
	    'options_global_menu_type' => 'hamburger',
	    'options_global_page_background_repeat' => 'repeat',
	    'options_global_page_background_size' => 'auto',
	    'options_global_page_brand_color' => '#444444',
	    'options_global_page_headings_typo' => '{"font_family":"Playfair Display","font_variants":["700","regular"],"font_subsets":["latin"]}',
	    'options_global_page_smooth_scroll' => '1',
	    'options_global_page_subtitles_typo' => '{"color":"#5a5a5a","font_family":"Rubik","font_variants":["regular","500","700"],"font_subsets":["latin"]}',
	    'options_global_post_title_background_color' => '',
	    '_options_global_post_title_background_color' => 'field_592d69654e10f',
	    'options_global_post_title_background_size' => 'cover',
	    '_options_global_post_title_background_size' => 'field_592d69e4383d6',
	    'options_global_post_title_background_type' => 'post_thumbnail',
	    'options_global_post_use_title_overlay' => '0',
	    '_options_global_post_use_title_overlay' => 'field_592d6dbf5673e',
	    'options_global_side_panel_add_padding' => '0',
	    'options_global_side_panel_background' => 'rgba(255,255,255,0.01)',
	    'options_global_side_panel_position' => 'right',
	    'options_global_side_panel_social' => 'a:4:{i:0;s:8:"facebook";i:1;s:7:"twitter";i:2;s:10:"googleplus";i:3;s:8:"linkedin";}',
	    'options_global_side_panel_text' => '&copy; 2017, Norebro theme by <a href="#" target="_blank">Colabr.io</a>',
	);