<?php

	$ocdi_fields_to_change = array(
	    'options_global_footer_background_color' => '#ffffff',
	    'options_global_footer_copyright_background_color' => '#ffffff',
	    'options_global_footer_copyright_left' => '&copy; 2017, Norebro Theme by <a href="#" target="_blank">Colabr.io Team</a> | <a href="#">Privacy Policy</a> | <a href="#">Sitemap</a>',
	    'options_global_footer_copyright_right' => 'All Rights Reserved.',
	    'options_global_footer_copyright_text' => '&copy; 2017, norebro theme by <a href="#" target="_blank">Colabr.io Team</a>, All right reserved.',
	    '_options_global_footer_copyright_text' => 'field_592fd8901f24b',
	    'options_global_footer_copyright_text_color' => '#9194a0',
	    'options_global_footer_is_sticky' => '1',
	    'options_global_footer_logo_image' => '1985',
	    '_options_global_footer_logo_image' => 'field_592fd8901c689',
	    'options_global_footer_logo_type' => 'custom',
	    'options_global_footer_text_color' => '#9194a0',
	    'options_global_fullscreen_menu_style' => 'default',
	    'options_global_fullscreen_menu_text_typo' => '',
	    'options_global_page_is_wrapped' => '1',
	    'options_global_header_logo_when_fixed' => 'dark_variant',
	    'options_global_header_menu_border_color' => 'rgba(0,0,0,0.06)',
	    'options_global_header_menu_border_type' => 'solid',
	    'options_global_header_menu_contacts_bar_additional' => '',
	    '_options_global_header_menu_contacts_bar_additional' => 'field_59229bda3630a',
	    'options_global_header_menu_contacts_bar_emails' => '',
	    '_options_global_header_menu_contacts_bar_emails' => 'field_59229bda35ef5',
	    'options_global_header_menu_contacts_bar_phone_numbers' => '',
	    '_options_global_header_menu_contacts_bar_phone_numbers' => 'field_59229bda35af2',
	    'options_global_header_menu_contacts_bar_social_links' => '',
	    '_options_global_header_menu_contacts_bar_social_links' => 'field_59229bda366f4',
	    'options_global_header_menu_fixed' => '0',
	    'options_global_header_menu_hide_border' => '0',
	    'options_global_header_menu_hide_contacts_bar' => '0',
	    'options_global_header_menu_social_links_1_social_network' => 'googleplus',
	    'options_global_header_menu_social_links_2_social_network' => 'dribbble',
	    'options_global_header_menu_text_typo' => '{}',
	    'options_global_header_title_align' => 'left',
	    'options_global_header_title_background_type' => 'image',
	    'options_global_logo_type' => 'sitename',
	    'options_global_menu_hamburger_align' => 'inside_panel',
	    'options_global_menu_type' => 'hamburger',
	    'options_global_page_background_repeat' => 'repeat',
	    'options_global_page_background_size' => 'auto',
	    'options_global_page_brand_color' => '#505cfd',
	    'options_global_page_headings_typo' => '{"weight":"600","font_family":"Poppins","font_variants":["700","600","500","regular","300"],"font_subsets":["latin-ext","latin","devanagari"]}',
	    'options_global_page_smooth_scroll' => '1',
	    'options_global_page_subtitles_typo' => '{"weight":"500","font_family":"Poppins","font_variants":["700","600","500","regular","300"],"font_subsets":["latin-ext","latin","devanagari"]}',
	    'options_global_page_text_typo' => '{"font_family":"Rubik","font_variants":["900italic","900","700italic","700","500italic","500","italic","regular","300italic","300"],"font_subsets":["cyrillic","latin-ext","hebrew","latin"]}',
	    'options_global_project_header_title_height_settings' => 'inherit',
	    '_options_global_project_header_title_height_settings' => 'field_59310b5b35a20',
	    'options_global_project_layout_type' => 'type_2',
	    'options_global_project_navigation_position' => 'bottom',
	    '_options_global_project_navigation_position' => 'field_592fd66622a31amod',
	    'options_global_project_show_navigation' => 'prev_n_next',
	    'options_global_project_social_sharing_buttons' => 'a:5:{i:0;s:8:"facebook";i:1;s:7:"twitter";i:2;s:10:"googleplus";i:3;s:9:"pinterest";i:4;s:8:"linkedin";}',
	    'options_global_side_panel_background' => '#ffffff',
	    'options_global_side_panel_social' => 'a:4:{i:0;s:8:"facebook";i:1;s:7:"twitter";i:2;s:10:"googleplus";i:3;s:8:"linkedin";}',
	    'options_global_side_panel_text' => '&copy; 2017, Norebro theme by <a href="#" target="_blank">Colabr.io</a>'
	);