<?php

	$ocdi_fields_to_change = array(
	    'options_global_page_background_size' => 'auto',
	    'options_global_page_background_repeat' => 'repeat',
	    'options_global_page_text_typo' => '{"color":"#656f74","font_family":"Rubik","font_variants":["300","300italic","regular","italic","500","500italic","700","700italic","900","900italic"],"font_subsets":["latin","hebrew","latin-ext","cyrillic"]}',
	    'options_global_page_headings_typo' => '{"color":"#333b3e","weight":"500","font_family":"Fjalla One","font_variants":["regular"],"font_subsets":["latin","latin-ext"]}',
	    'options_global_page_subtitles_typo' => '{"color":"#687277","font_family":"Rubik","font_variants":["300","300italic","regular","italic","500","500italic","700","700italic","900","900italic"],"font_subsets":["latin","hebrew","latin-ext","cyrillic"]}',
	    'options_global_page_smooth_scroll' => '1',
	    'options_global_page_custom_css' => '.header-title h1.page-title {text-transform:uppercase;}',
	    'options_global_logo_type' => 'sitename',
	    'options_global_page_is_wrapped' => '1',
	    'options_global_header_menu_logo_typo' => '{"color":"#333333"}',
	    'options_global_menu_type' => 'hamburger',
	    'options_global_header_menu_fixed' => '0',
	    'options_global_header_menu_text_typo' => '{"color":"#333b3e"}',
	    'options_global_header_menu_hide_border' => '0',
	    'options_global_header_menu_hide_contacts_bar' => '0',
	    'options_global_header_menu_contacts_bar_phone_numbers' => '1',
	    '_options_global_header_menu_contacts_bar_phone_numbers' => 'field_59229bda35af2',
	    'options_global_header_menu_contacts_bar_emails' => '1',
	    '_options_global_header_menu_contacts_bar_emails' => 'field_59229bda35ef5',
	    'options_global_header_menu_contacts_bar_additional' => 'Business Hours: 10.00 am - 08.00 pm',
	    '_options_global_header_menu_contacts_bar_additional' => 'field_59229bda3630a',
	    'options_global_header_menu_contacts_bar_social_links' => '',
	    '_options_global_header_menu_contacts_bar_social_links' => 'field_59229bda366f4',
	    'options_global_header_menu_contacts_bar_background' => '#ffffff',
	    'options_global_header_menu_contacts_bar_text_typo' => '{"size":"12px","color":"#435055","height":"32px","font_family":"Fjalla One","font_variants":["regular"],"font_subsets":["latin"]}',
	    'options_global_header_background_color' => '#f6f9fc',
	    'options_global_header_title_background_image' => '10028',
	    'options_global_header_use_overlay' => '0',
	    'options_global_header_tilte_typo' => '{"color":"#333b3e"}',
	    'options_global_header_subtilte_typo' => '{"color":"#687277"}',
	    'options_global_header_height' => '400px',
	    'options_global_header_logo_by_default' => 'dark_variant',
	    'options_global_header_logo_when_fixed' => 'dark_variant',
	    'options_global_header_menu_border_type' => 'solid',
	    'options_global_header_menu_border_color' => 'rgba(0,0,0,0.04)',
	    'options_global_header_menu_contacts_bar_phone_numbers_0_phone_numbers' => 'Online Appointment',
	    '_options_global_header_menu_contacts_bar_phone_numbers_0_phone_numbers' => 'field_59229bda6c954',
	    'options_global_header_menu_contacts_bar_emails_0_emails' => '',
	    '_options_global_header_menu_contacts_bar_emails_0_emails' => 'field_59229bda725e5',
	    'options_global_footer_background_color' => '#333b3e',
	    'options_global_footer_is_sticky' => '1',
	    'options_global_footer_copyright_left' => '&copy; 2017, Norebro Theme by <a href="#" target="_blank">Colabr.io Team</a> | <a href="#">Privacy Policy</a> | <a href="#">Sitemap</a>',
	    'options_global_footer_copyright_right' => 'All Rights Reserved.',
	    'options_global_footer_copyright_text_color' => '#656f74',
	    'options_global_footer_copyright_background_color' => '#333b3e',
	    'options_global_footer_logo_type' => 'custom',
	    'options_global_side_panel_add_padding' => '0',
	    'options_global_side_panel_background' => 'rgba(255,255,255,0.01)',
	    'options_global_side_panel_separator' => '#333b3e',
	    'options_global_side_panel_text' => '&copy; 2017, Norebro theme by <a href="#" target="_blank">Colabr.io</a>',
	    'options_global_side_panel_social' => 'a:4:{i:0;s:8:"facebook";i:1;s:7:"twitter";i:2;s:10:"googleplus";i:3;s:8:"linkedin";}',
	    'options_global_fullscreen_menu_style' => 'default',
	    'options_global_fullscreen_menu_text_typo' => '',
	    'options_global_header_menu_social_links_0_url' => 'https://www.facebook.com/',
	    'options_global_header_menu_social_links_1_social_network' => 'instagram',
	    'options_global_header_menu_social_links_1_url' => 'https://www.facebook.com/',
	    'options_global_header_menu_social_links_2_social_network' => 'twitter',
	    'options_global_header_menu_social_links_2_url' => 'https://www.facebook.com/',
	    'options_global_header_menu_subheader_items_left_0_items' => '<a href="#">ONLINE APPOINTMENT</a>',
	    '_options_global_header_menu_subheader_items_left_0_items' => 'field_59229bda6c954',
	    'options_global_header_menu_subheader_items_left' => '1',
	    'options_global_header_menu_subheader_items_right_0_items' => 'BUSINESS HOURS: 10.00 AM - 08.00 PM',
	    '_options_global_header_menu_subheader_items_right_0_items' => 'field_59229bda6c955',
	    'options_global_header_menu_subheader_items_right' => '1',
	);