<?php

	$ocdi_fields_to_change = array(
	  'options_global_page_is_wrapped' => '1',
	  'options_global_page_brand_color' => '#84625a',
	  'options_global_page_background_size' => 'auto',
	  'options_global_page_background_repeat' => 'repeat',
	  'options_global_page_text_typo' => '{"size":"15px","font_family":"Rubik","font_variants":["300","300italic","regular","italic","500","500italic","700","700italic","900","900italic"],"font_subsets":["latin","hebrew","latin-ext","cyrillic"]}',
	  'options_global_page_headings_typo' => '{"weight":"500","font_family":"Oswald","font_variants":["700","600","500","regular","300","200"],"font_subsets":["cyrillic","latin-ext","vietnamese","latin"]}',
	  'options_global_page_subtitles_typo' => '{"font_family":"Rubik","font_variants":["900italic","900","700italic","700","500italic","500","italic","regular","300italic","300"],"font_subsets":["cyrillic","latin-ext","hebrew","latin"]}',
	  'options_global_page_show_breadcrumbs' => '0',
	  'options_global_page_smooth_scroll' => '1',
	  'options_global_page_custom_css' => '.header-title h1.page-title {, text-transform: uppercase;, }',
	  'options_global_footer_is_sticky' => '1',
	  'options_global_footer_copyright_text' => '&copy; 2017, Norebro theme by <a href="#" target="_blank">Colabr.io Team</a>, All right reserved.',
	  '_options_global_footer_copyright_text' => 'field_592fd8901f24b',
	  'options_global_logo_type' => 'sitename',
	  'options_global_header_logo_when_fixed' => 'dark_variant',
	  'options_global_header_menu_fixed' => '0',
	  'options_global_header_menu_border_type' => 'solid',
	  'options_global_header_menu_height' => '100',
	  'options_global_header_menu_hide_contacts_bar' => '0',
	  'options_global_header_menu_contacts_bar_phone_numbers' => '1',
	  '_options_global_header_menu_contacts_bar_phone_numbers' => 'field_59229bda35af2',
	  'options_global_header_menu_contacts_bar_emails' => '',
	  '_options_global_header_menu_contacts_bar_emails' => 'field_59229bda35ef5',
	  'options_global_header_menu_contacts_bar_additional' => 'Online Appointment',
	  '_options_global_header_menu_contacts_bar_additional' => 'field_59229bda3630a',
	  'options_global_header_menu_contacts_bar_social_links' => '',
	  '_options_global_header_menu_contacts_bar_social_links' => 'field_59229bda366f4',
	  'options_global_header_menu_contacts_bar_background' => '#333333',
	  'options_global_header_menu_contacts_bar_text_typo' => '{"size":"12px","color":"#999999","height":"32px","font_family":"Oswald","font_variants":["700","600","500","regular","300"],"font_subsets":["latin"]}',
	  'options_global_header_title_background_type' => 'image',
	  'options_global_header_tilte_typo' => '{"size":"46px","weight":"400"}',
	  'options_global_header_title_align' => 'left',
	  'options_global_header_height' => '480px',
	  'options_global_side_panel_position' => 'hide',
	  'options_global_side_panel_text' => '&copy; 2017, Norebro theme by <a href="#" target="_blank">Colabr.io Team</a>, All right reserved.',
	  'options_global_side_panel_social' => 'a:4:{i:0;s:8:"facebook";i:1;s:7:"twitter";i:2;s:10:"googleplus";i:3;s:8:"linkedin";}',
	  'options_global_header_menu_contacts_bar_phone_numbers_0_phone_numbers' => '+46 (062) 450 45 45',
	  '_options_global_header_menu_contacts_bar_phone_numbers_0_phone_numbers' => 'field_59229bda6c954',
	  'options_global_footer_copyright_left' => '&copy; 2017, Norebro Theme by <a href="#" target="_blank">Colabr.io Team</a> | <a href="#">Privacy Policy</a> | <a href="#">Sitemap</a>',
	  'options_global_footer_copyright_right' => 'All Rights Reserved.',
	  'options_global_fullscreen_menu_style' => 'default',
	  'options_global_fullscreen_menu_text_typo' => '',
	  'options_global_header_menu_social_links_1_social_network' => 'googleplus',
	  'options_global_header_menu_social_links_2_social_network' => 'instagram',
	  'options_global_header_menu_subheader_items_left_0_items' => '+46 (062) 450 45 45',
	  '_options_global_header_menu_subheader_items_left_0_items' => 'field_59229bda6c954',
	  'options_global_header_menu_subheader_items_left_1_items' => '<a href="/demo14/barbers/">ONLINE APPOINTMENT</a>',
	  '_options_global_header_menu_subheader_items_left_1_items' => 'field_59229bda6c954',
	  'options_global_header_menu_subheader_items_left' => '2',
	  'options_global_header_menu_subheader_items_right_0_items' => 'BUSINESS HOURS: 10.00 AM - 08.00 PM',
	  '_options_global_header_menu_subheader_items_right_0_items' => 'field_59229bda6c955',
	  'options_global_header_menu_subheader_items_right' => '1',
	);