<?php

	$ocdi_fields_to_change = array(
	    'options_global_header_menu_style' => 'style2',
	    'options_global_logo_type' => 'sitename',
	    'options_global_header_menu_logo_typo' => '{"color":"#333333"}',
	    'options_global_header_menu_add_cap' => 'yes',
	    'options_global_header_menu_background_color' => '#f9f9f9',
	    'options_global_header_menu_text_typo' => '{"color":"#333333"}',
	    'options_global_header_menu_border_type' => 'solid',
	    'options_global_header_menu_hide_contacts_bar' => '0',
	    'options_global_header_menu_contacts_bar_phone_numbers' => '',
	    '_options_global_header_menu_contacts_bar_phone_numbers' => 'field_59229bda35af2',
	    'options_global_header_menu_contacts_bar_emails' => '',
	    '_options_global_header_menu_contacts_bar_emails' => 'field_59229bda35ef5',
	    'options_global_header_menu_contacts_bar_additional' => '',
	    '_options_global_header_menu_contacts_bar_additional' => 'field_59229bda3630a',
	    'options_global_header_menu_contacts_bar_social_links' => '',
	    '_options_global_header_menu_contacts_bar_social_links' => 'field_59229bda366f4',
	    'options_global_header_title_background_type' => 'image',
	    'options_global_header_background_color' => '#ffffff',
	    'options_global_header_title_background_image' => '72',
	    'options_global_header_title_background_position' => 'left_top',
	    'options_global_header_use_overlay' => '0',
	    'options_global_header_tilte_typo' => '{"color":"#333333"}',
	    'options_global_header_subtilte_typo' => '{"color":"#333333"}',
	    'options_global_header_title_align' => 'left',
	    'options_global_header_height' => '360px',
	    'options_global_page_brand_color' => '#505cfd',
	    'options_global_page_background_size' => 'auto',
	    'options_global_page_background_repeat' => 'repeat',
	    'options_global_page_text_typo' => '{"font_family":"Rubik","font_variants":["900italic","900","700italic","700","500italic","500","italic","regular","300italic","300"],"font_subsets":["cyrillic","latin-ext","hebrew","latin"]}',
	    'options_global_page_headings_typo' => '{"color":"#333333","font_family":"Poppins","font_variants":["300","regular","500","600","700"],"font_subsets":["devanagari","latin","latin-ext"]}',
	    'options_global_page_subtitles_typo' => '{"color":"#585858","font_family":"Playfair Display","font_variants":["regular","italic","700","700italic","900","900italic"],"font_subsets":["latin","latin-ext","cyrillic"]}',
	    'options_global_page_show_breadcrumbs' => '0',
	    'options_global_page_smooth_scroll' => '1',
	    'options_global_header_logo_by_default' => 'dark_variant',
	    'options_global_page_is_wrapped' => '1',
	    'options_global_header_logo_when_fixed' => 'dark_variant',
	    'options_global_side_panel_add_padding' => '0',
	    'options_global_side_panel_background' => 'rgba(255,255,255,0.01)',
	    'options_global_side_panel_text' => '&copy; 2017, Norebro theme by <a href="#" target="_blank">Colabr.io</a>',
	    'options_global_side_panel_social' => 'a:4:{i:0;s:8:"facebook";i:1;s:7:"twitter";i:2;s:10:"googleplus";i:3;s:8:"linkedin";}',
	    'options_global_fullscreen_menu_style' => 'default',
	    'options_global_footer_is_sticky' => '1',
	    'options_global_footer_copyright_left' => '&copy; 2017, Norebro Theme by <a href="#" target="_blank">Colabr.io Team</a> | <a href="#">Privacy Policy</a> | <a href="#">Sitemap</a>',
	    'options_global_footer_copyright_right' => 'All Rights Reserved.',
	    'options_global_footer_logo_type' => 'custom',
	    'options_global_fullscreen_menu_text_typo' => '',
	    'options_global_header_menu_social_links_0_social_network' => 'twitter',
	    'options_global_header_menu_social_links_1_social_network' => 'instagram',
	    'options_global_header_menu_social_links_2_social_network' => 'googleplus'
	);