<?php
	// slider revolution slides
	$ocdi_slides_to_revolution = array(
		trailingslashit( get_template_directory() ) . 'demo/25/home_slider.zip'
	);

	$ocdi_fields_to_change = array(
	    'options_global_page_brand_color' => '#505cfd',
	    'options_global_page_background_size' => 'auto',
	    'options_global_page_background_repeat' => 'repeat',
	    'options_global_page_text_typo' => '{"font_family":"Rubik","font_variants":["300","regular","500","700","900"],"font_subsets":["latin"]}',
	    'options_global_page_headings_typo' => '{"weight":"400","font_family":"Poppins","font_variants":["300","regular","500","600","700"],"font_subsets":["latin"]}',
	    'options_global_page_subtitles_typo' => '{"weight":"500","font_family":"Poppins","font_variants":["300","regular","500","600","700"],"font_subsets":["latin"]}',
	    'options_global_page_smooth_scroll' => '1',
	    'options_global_side_panel_position' => 'hide',
	    'options_global_side_panel_text' => '&copy; 2017, Norebro theme by <a href="#" target="_blank">Colabr.io Team</a>, All right reserved.',
	    'options_global_side_panel_social' => 'a:4:{i:0;s:8:"facebook";i:1;s:7:"twitter";i:2;s:10:"googleplus";i:3;s:8:"linkedin";}',
	    'options_global_header_menu_style' => 'style2',
	    'options_global_logo_type' => 'sitename',
	    'options_global_header_logo_by_default' => 'dark_variant',
	    'options_global_header_logo_when_fixed' => 'dark_variant',
	    'options_global_page_is_wrapped' => '1',
	    'options_global_menu_type' => 'hamburger',
	    'options_global_header_menu_fixed' => '0',
	    'options_global_header_menu_use_wrapper' => '0',
	    'options_global_header_menu_background_color' => '#ffffff',
	    'options_global_header_menu_border_type' => 'solid',
	    'options_global_header_menu_hide_contacts_bar' => '0',
	    'options_global_header_menu_contacts_bar_phone_numbers' => '',
	    '_options_global_header_menu_contacts_bar_phone_numbers' => 'field_59229bda35af2',
	    'options_global_header_menu_contacts_bar_emails' => '',
	    '_options_global_header_menu_contacts_bar_emails' => 'field_59229bda35ef5',
	    'options_global_header_menu_contacts_bar_additional' => '',
	    '_options_global_header_menu_contacts_bar_additional' => 'field_59229bda3630a',
	    'options_global_header_menu_contacts_bar_social_links' => '',
	    '_options_global_header_menu_contacts_bar_social_links' => 'field_59229bda366f4',
	    'options_global_header_background_color' => '#f9f9f9',
	    'options_global_header_tilte_typo' => '{"color":"#404044"}',
	    'options_global_header_subtilte_typo' => '{"color":"rgba(64,64,68,0.6)"}',
	    'options_global_header_title_align' => 'left',
	    'options_global_header_height' => '380px',
	    'options_global_side_panel_add_padding' => '0',
	    'options_global_fullscreen_menu_style' => 'default',
	    'options_global_footer_copyright_left' => '&copy; 2017, Norebro Theme by <a href="#" target="_blank">Colabr.io Team</a> | <a href="#">Privacy Policy</a> | <a href="#">Sitemap</a>',
	    'options_global_footer_copyright_right' => 'All Rights Reserved.',
	    'options_global_footer_copyright_text_color' => '#595959',
	    'options_global_footer_copyright_background_color' => '#ffffff',
	    'options_global_fullscreen_menu_text_typo' => '',
	    'options_global_header_menu_social_links' => '',
	);